# Generated by Django 4.0.2 on 2022-02-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(help_text='Пожалуйста, укажите свой пароль', max_length=15, unique=True),
        ),
    ]
