# Generated by Django 4.0.2 on 2022-02-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0002_typedoctor_doctor_created_at_doctor_description_and_more'),
        ('account', '0003_alter_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='favorite_doctor',
            field=models.ManyToManyField(blank=True, related_name='doktr', to='specialist.Doctor'),
        ),
    ]
