# Generated by Django 4.0.2 on 2022-02-10 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_countymodel_name_en_countymodel_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.regionmodel'),
        ),
    ]
