# Generated by Django 4.0.2 on 2022-02-10 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('shop', '0001_initial'),
        ('account', '0005_usermodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='favorite_doctor',
            field=models.ManyToManyField(to='consultation.Doctor'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='favorite_medicine',
            field=models.ManyToManyField(to='shop.Medicine'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='language',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='theme_mode',
            field=models.SmallIntegerField(choices=[(2, 'Black'), (1, 'White')], db_index=True, default=1),
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_address', models.CharField(blank=True, max_length=255, null=True)),
                ('apartment_office', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(blank=True, max_length=255, null=True)),
                ('door_or_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('instructions', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
