# Generated by Django 4.0.2 on 2022-03-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_ordermodel_credit_card'),
        ('account', '0006_alter_usermodel_avatar_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
