# Generated by Django 4.0.2 on 2022-02-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('shop', '0001_initial'),
        ('account', '0007_alter_usermodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='favorite_doctor',
            field=models.ManyToManyField(blank=True, to='consultation.Doctor'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='favorite_medicine',
            field=models.ManyToManyField(blank=True, to='shop.Medicine'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='language',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
