# Generated by Django 4.0.2 on 2022-03-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_regionmodel_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.regionmodel'),
        ),
    ]
