# Generated by Django 4.0.2 on 2022-03-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_ordermodel_shipping_address'),
        ('specialist', '0004_ratedoctor_created_at_advicetime'),
        ('account', '0009_deliveryaddress_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='favorite_doctor',
            field=models.ManyToManyField(blank=True, related_name='fav_dock', to='specialist.Doctor'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='favorite_medicine',
            field=models.ManyToManyField(blank=True, related_name='fav_med', to='shop.Medicine'),
        ),
    ]
