# Generated by Django 4.0.2 on 2022-10-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_offermodel_alter_usermodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/2022-10-10/'),
        ),
    ]
