# Generated by Django 4.0.2 on 2022-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsmodel_description_en_newsmodel_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/2022-3-3/'),
        ),
    ]
