# Generated by Django 4.0.2 on 2022-07-18 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='news.tagsmodel'),
        ),
    ]
