# Generated by Django 4.0.2 on 2022-07-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_tagsmodel_alter_newsmodel_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsmodel',
            name='tag_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tagsmodel',
            name='tag_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tagsmodel',
            name='tag_name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
