# Generated by Django 4.0.2 on 2022-09-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_tagsmodel_tag_name_en_tagsmodel_tag_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/2022-9-9/'),
        ),
    ]
