# Generated by Django 4.0.2 on 2022-09-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_delete_advertising'),
        ('specialist', '0006_advicetime_end_time_advicetime_status'),
        ('news', '0008_alter_newsmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine/advertising/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('type', models.SmallIntegerField(choices=[(1, 'medicines'), (2, 'doctors')], db_index=True, default=1)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='special_news_doc', to='specialist.doctor')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='special_news_med', to='shop.medicine')),
            ],
        ),
    ]
