# Generated by Django 4.0.2 on 2022-10-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_advertising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/2022-10-10/'),
        ),
    ]
