# Generated by Django 4.0.2 on 2022-02-16 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='message/images/2022-2-2/')),
                ('file', models.FileField(blank=True, null=True, upload_to='message/files/2022-2-2/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chat_client', to=settings.AUTH_USER_MODEL)),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chat_doctor', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(related_name='words', to='chat.Message')),
            ],
        ),
    ]
