# Generated by Django 4.0.2 on 2022-02-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='msg',
            new_name='text',
        ),
    ]
