# Generated by Django 4.0.2 on 2022-03-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_file_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
