# Generated by Django 4.0.2 on 2022-10-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_file_alter_message_image'),
        ('chat', '0008_chatroom_token_alter_message_file_and_more'),
    ]

    operations = [
    ]
