# Generated by Django 4.0.2 on 2022-03-09 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialist', '0002_typedoctor_doctor_created_at_doctor_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=4)),
                ('feedback', models.SmallIntegerField(choices=[(1, 'Not Bad'), (2, 'Love it'), (3, 'Nice Work'), (4, 'Awesome')], default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='specialist.doctor')),
            ],
        ),
    ]
