# Generated by Django 4.0.2 on 2022-09-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0005_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='advicetime',
            name='end_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advicetime',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
