# Generated by Django 4.0.2 on 2022-02-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicturesMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_pictures/2022-2-2/')),
            ],
        ),
        migrations.CreateModel(
            name='TypeMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='types/')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine /')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('order_count', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('review', models.IntegerField(default=0)),
                ('cost', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('pictures', models.ManyToManyField(to='shop.PicturesMedicine')),
                ('type_medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.typemedicine')),
            ],
        ),
    ]
