# Generated by Django 4.0.2 on 2022-02-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_medicine_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='shop.PicturesMedicine'),
        ),
    ]
