# Generated by Django 4.0.2 on 2022-02-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_medicine_description_en_medicine_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
