# Generated by Django 4.0.2 on 2022-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_medicine_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturesmedicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_pictures/2022-3-3/'),
        ),
    ]
