# Generated by Django 4.0.2 on 2022-03-06 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_usermodel_avatar_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_cartmodel_status_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='credit_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.card'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
