# Generated by Django 4.0.2 on 2022-03-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_ordermodel_credit_card_alter_ordermodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='amount',
            new_name='price',
        ),
    ]
