# Generated by Django 4.0.2 on 2022-03-07 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_usermodel_avatar_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_rename_amount_ordermodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.medicine'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='credit_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.card'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.deliveryaddress'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
