# Generated by Django 4.0.2 on 2022-03-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymeuz', '0002_card'),
        ('shop', '0011_alter_cartmodel_product_alter_ordermodel_credit_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='credit_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='paymeuz.card'),
        ),
    ]
