# Generated by Django 4.0.2 on 2022-03-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_regionmodel_delivery_price'),
        ('shop', '0013_deliveryman_ordermodel_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.deliveryaddress'),
        ),
    ]
