# Generated by Django 4.0.2 on 2022-06-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_ordermodel_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='picturesmedicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_pictures/2022-6-6/'),
        ),
    ]
