# Generated by Django 4.0.2 on 2022-06-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_medicine_weight_alter_picturesmedicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemedicine',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='types/icons/'),
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine/advertising/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.medicine')),
            ],
        ),
    ]
