# Generated by Django 4.0.2 on 2022-09-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_picturesmedicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='picturesmedicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_pictures/2022-9-9/'),
        ),
    ]
