# Generated by Django 4.0.2 on 2022-09-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_cartmodel_amount_alter_picturesmedicine_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertising',
        ),
    ]
