# Generated by Django 4.0.2 on 2022-03-07 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymeuz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('expire', models.CharField(max_length=4)),
                ('token', models.CharField(max_length=4)),
                ('recurrent', models.BooleanField()),
                ('verify', models.BooleanField()),
                ('type', models.SmallIntegerField(choices=[(1, 'Black'), (2, 'White')], default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
