# Generated by Django 4.0.2 on 2022-03-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymeuz', '0002_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
        migrations.AlterField(
            model_name='card',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
