# Generated by Django 4.0.2 on 2022-07-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_commentdoctor_rate_commentmedicine_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdoctor',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
