# Generated by Django 4.0.2 on 2022-07-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_commentdoctor_user_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commentdoctor',
            constraint=models.UniqueConstraint(fields=('doctor', 'user'), name='rate_doc'),
        ),
        migrations.AddConstraint(
            model_name='commentmedicine',
            constraint=models.UniqueConstraint(fields=('medicine', 'user'), name='rate_med'),
        ),
    ]
