# Generated by Django 4.0.2 on 2022-09-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_commentdoctor_rate_doc_commentmedicine_rate_med'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.BooleanField(default=False)),
            ],
        ),
    ]
